#!/usr/bin/env bash
#Install nginx web server

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start
Target_string="a\\\trewrite ^/redirect_me https://youtube.com/watch?v=QH2-TGU1wu4 permanent;"
sudo sed -i "s/server_name _;/$Target_string/" /etc/nginx/site-enabled/default
sudo service nginx restart
