#!/usr/bin/env bash
#Redirection

#Update packages
apt-get update
apt-get install -y nginx

#Create an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

#Handle redirects
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/MutabPato permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#Restart Nginx service
service nginx restart
