#!/usr/bin/env bash
#Redirection 301 moved permanently

#Update packages
sudo apt-get update
sudo apt-get install -y nginx

#Create an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

#Handle redirects
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/MutabPato permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

#Restart Nginx service
sudo service nginx restart
