#!/usr/bin/env bash
#Configure Nginx

apt-get update
apt-get -y install nginx

string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/"/etc/nginx/nginx.conf

sudo service nginx restart
