#!/usr/bin/env bash
#MySQL backup

current_date=$(date +"%d-%m-%Y")

dump_file="backup.sql"

archive_file="$current_date.tar.gz"

# MySQL dump command
mysqldump --all-databases -u root -p"$1" > "dump_file"

# Create compressed file
tar -czf "$archive_file" "$dump_file"
