#!/usr/bin/env bash
#MySQL backup

current_date=$(date +"%d-%m-%Y")

archive_file="$current_date.tar.gz"

# MySQL dump command
mysqldump --all-databases -u root -p"$1" > backup.sql

# Create compressed file
tar -czvf "$archive_file" backup.sql
