#!/usr/bin/env bash
# displays Best School 10 times
i=1
while [ "$i" -le 20 ];do
	echo "$i"
	case "$i" in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck Japan"
			;;
		"17")
			echo "bad luck Italy"
			;;
	esac
	((i++))
done
