#!/usr/bin/env bash
#configures an Ubuntu server

if [ "$EUID" -ne 0 ]; then
	exit 1
fi 

cp /etc/hosts ~/hosts.new

sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\localhost/' ~/hosts.new
sed -i '/facebook.com/s/\b[0-9.]\+\b/8.8.8.8/' ~/hosts.new

cat /etc/hosts
