#!/usr/bin/env bash
#configures an Ubuntu server

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2	localhost/' ~/hosts.new
sed -i 's/157.240.11.35/8.8.8.8	facebook.com/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
