#!/usr/bin/env bash
# creates an RSA key pair

if [ -f ~/.ssh/school ]; then
	echo "Key file ~/.ssh/school already exists."
	exit 1
fi

ssh-keygen -t rsa -b 4096 -N 'betty' -f school

echo "RSA key pair created successfully."
